sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.24.1

  before_install:
    - sudo rm /usr/local/bin/docker-compose
    - curl -L 
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin

  before_script:
    - docker-compose up -d --build

  script:
    - docker-compose exec users python manage.py test
    - docker-compose exec users flake8 project

  after_script:
    - docker-compose down
